### ISSUE TITLE
Mind map: Community growth and needs

### ISSUE THREAD

**Issue by Sander3003** [openscd/.community#20]
As a contributor
I would like to know what it takes to get community growth and what services are needed to support the community
So I understand the relations between them

**Comment by Sander3003** [comment]
https://wiki.lfenergy.org/display/SHP/OpenSCD+Growth+and+needs

**Comment by benvantende** [comment]
Also, added a nice graphical overview, that you can also find on above mentioned WIKI page.
![Mind Map Community Support](https://github.com/openscd/.community/assets/296888/f9fcee83-d92a-4aac-b472-d62b32d05457)
