### ISSUE TITLE
Workshop: Svelte

### ISSUE THREAD

**Issue by benvantende** [openscd/.community#21]
https://svelte.dev/
Tamás works a lot with Svelte and would like to present how they use it at SprintEins. @trusz can you describe, for the team, what you would like to explore and communicate with this workshop?

**Comment by trusz** [comment]
Next step is to find all interested parties and find a date for it

**Comment by benvantende** [comment]
Workshop will be Thursday October 26, 10:00 - 11:30

![Image](https://github.com/openscd/.community/assets/296888/d75ace93-dc19-4816-9563-15fc79b2cd48)

**Comment by benvantende** [comment]
Gteat workshop thanks!
