### ISSUE TITLE
OpenSCD - LF Energy Umbrella Consensus

### ISSUE THREAD

**Issue by benvantende** [openscd/.community#24]
Over the course of the past months, the OpenSCD team, consisting of product owners and developers of the various companies working on OpenSCD, have been discussing joining LF Energy. There are many upsides to joining LF Energy, like using their infrastructure, design resources, marketing etc. We have made sure in our discussions that everyone understands that LF Energy does not take any specific role in the project itself, but is just there to facilitate. Now we are at the point where all signs are green, and we would also like to confirm our intention with the community, so this is saved for generations to come ;)

A simple YES will do to confirm, but there is no-one stopping you to adding additional remarks in the form of nice words. 

SAY YES HERE ⇩

**Comment by trusz** [comment]
YES 👍

**Comment by benvantende** [comment]
YES ⇩

**Comment by pascalwilbrink** [comment]
YES 💙

**Comment by Stef3st** [comment]
YES :tada:

**Comment by juancho0202** [comment]
YES

**Comment by Sander3003** [comment]
YES

**Comment by danyill** [comment]
(I am perhaps less convinced than others) but happy to work with a rough consensus which seems to be a an upper-case  yes.

LF Energy seem friendly and open and there don't seem to be additional costs or difficulties in leaving should we change our mind later on. I agree in particular that having a neutral third party to hold secrets, domain registrations etc. would be helpful.

I expect in standups while I've been away the specific question of what we'll be doing differently after gaining LF Energy membership and how we'll ensure that adds value has been explored.

**Comment by pire13** [comment]
I don't see as much benefit as others, but I don't want to prevent others from getting the benefits for OpenSCD they expect. So, under the condition that Omicron keeps the same rights and can do the same with OpenSCD as we could do now, I agree to the OpenSCD project to join LF Energy.
However, if a part of the LF Energy contributors see no or too few use cases for OpenSCD outside of CoMAS and therefore make efforts to merge OpenSCD into/and CoMPAS, the contributors who do not support this merge should be allowed to take OpenSCD out of LF Energy and continue development outside of LF Energy, while CoMPAS can continue as CoMPAS within LF Energy.
